import cb from 'classnames/bind';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { ReactNode } from 'react';
import Footer from '../Footer';
import Header from '../Header';
import styles from './Layout.module.scss';

const cn = cb.bind(styles);

interface LayoutProps {
    children: ReactNode;
    title: string;
}

const Layout = (props: LayoutProps) => {
    const { children, title } = props;
    const router = useRouter();

    return (
        <>
            <Head>
                <title>
                    Create Next App
                    {router.pathname === '/' ? '' : ` | ${title}`}
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={cn('container')}>
                <Header />
                <div className={cn('body')}>
                    <h1 className={cn('page-title', 'page-title-primary')}>
                        {title}
                    </h1>
                    {children}
                </div>
                <Footer />
            </div>
        </>
    );
};

export default Layout;
