import cb from "classnames/bind";
import Footer from "components/footer/footer";
import Navbar from "components/navbar/navbar";
import ScrollToTopBtn from "components/scrollToTopBtn/scrollToTopBtn";
import useDarkMode from "hooks/useDarkMode";
import Head from "next/head";
import { useRouter } from "next/router";
import { HtmlHTMLAttributes, ReactNode, useEffect, useState } from "react";

import styles from "./layout.module.scss";

const cn = cb.bind(styles);

interface LayoutProps extends HtmlHTMLAttributes<HTMLDivElement> {
    title: string;
}

const Layout = (props: LayoutProps) => {
    const { title } = props;
    const router = useRouter();
    const isDarkMode = useDarkMode();
    const [isLaod, setIsLoad] = useState(false);

    useEffect(() => {
        setIsLoad(true);
    }, [router]);

    return (
        <>
            <Head>
                <title>
                    Create Next App
                    {router && router.pathname === "/" ? "" : ` | ${title}`}
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="theme-color"
                    content={isDarkMode ? "#272727" : "#fff"}
                />

                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className={cn("container", isLaod && "animated")}>
                <div className={cn("body", props.className)}>
                    {props.children}
                </div>
            </div>
            <Footer />
            <ScrollToTopBtn />
        </>
    );
};

export default Layout;
