import cb from "classnames/bind";
import Footer from "components/footer/footer";
import Navbar from "components/navbar/navbar";
import ScrollToTopBtn from "components/scrollToTopBtn/scrollToTopBtn";
import useDarkMode from "hooks/useDarkMode";
import Head from "next/head";
import { useRouter } from "next/router";
import { ReactNode } from "react";

import styles from "./layout.module.scss";

const cn = cb.bind(styles);

interface LayoutProps {
    children: ReactNode;
    title: string;
}

const Layout = (props: LayoutProps) => {
    const { children, title } = props;
    const router = useRouter();
    const isDarkMode = useDarkMode();

    return (
        <>
            <Head>
                <title>
                    Create Next App
                    {router && router.pathname === "/" ? "" : ` | ${title}`}
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="theme-color"
                    content={isDarkMode ? "#272727" : "#fff"}
                />

                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={cn("container")}>
                <Navbar />
                <div className={cn("body")}>{children}</div>
                <Footer />
            </div>
            <ScrollToTopBtn />
        </>
    );
};

export default Layout;
